### ISSUE TITLE
Option to start a blank fresh project.

### ISSUE THREAD

**Issue by PhiRequiem** [ConexoLA/RAWRR#1]
I couldn't find an option to start a blank fresh project,  I couldn't find an option to start a blank fresh project, it could be a good item for manage different process

**Comment by Alekxanderz** [comment]
Hello @PhiRequiem 

Thank you for your suggestion! We will be working on this feature over the next couple of weeks. We'll let you know when the feature is ready.

Feel free to leave any additional feedback or comments, we really appreciate it! 🤗

**Comment by Alekxanderz** [comment]
Thank you again for your suggestion, we really appreciate it!

I'll be merging the changes into the main branch and closing the issue.
