### ISSUE TITLE
Importing v1.1.0 database exports to v1.2.0

### ISSUE THREAD

**Issue by lucastx** [ConexoLA/RAWRR#10]
Hello!

I just compiled and ran the pre-release v1.2.0. Thanks a lot for the updates, it seems great that localization customizing will be done in the app itself :-)

I tried importing the database I have in the v1.1.0 version here, but it seems to not be importing into the pre-release version. I wonder if there are plans to do this in the final release.

Steps to reproduce:

1. Load test database into v1.1.0 and export it
2. Download pre-release v1.2.0 on LInux
3. Compile  it using `npm install; npm run electron:build`
4. Run the .appImage file
5. Import the database exported in first step
6. Error presented: "File could not be imported. Please try again with a valid database"

[rawrr_1.1.0.db.zip](https://github.com/ConexoLA/RAWRR/files/7715650/rawrr_1.1.0.db.zip)

**Comment by Alekxanderz** [comment]
Hi, @lucastx!

We redesigned the database to be able to add some of the new features, backwards compatibility with old database versions is not intended. I suggest exporting the old data as a report and then manually importing it (copy and paste) in a clean version of the new database.
