### ISSUE TITLE
mac and windows installers built on linux problematic.

### ISSUE THREAD

**Issue by killapop** [ConexoLA/RAWRR#2]
Hi,
thanks for the good work.

I run debian stretch and am trying to build the installers for all targets. Linux Appimage works fine, .app for mac and .exe for windows have blank pages for all items in the menu except "Reports"

The build process shows no errors and goes through with the command

`npm run electron:build --linux --win --mac`

Is there something else I need to be do or do the installers for other platforms have to be built on the platforms themselves?

**Comment by Alekxanderz** [comment]
Hi @killapop 

What we do is run `npm run electron:build` on each platform. This approach is confirmed to work, but we're aware it's not ideal. Which is why we'll look into it and post any findings here, if we're successful, we'll update our readme with instructions on how to build for multiple platforms at the same time.

Thank you for taking the time to report the issue!

**Comment by killapop** [comment]
thanks for the reply @Alekxanderz 

I'm also doing some testing to get this to work. will update you with my findings if I manage it :)

**Comment by killapop** [comment]
Thanks for the update @Alekxanderz 

I used your instructions and they worked quite well. 
I am building on debian buster. node v12.19.0 for Windows 10 and Intel Mac using the following:

I first fetched and checked out branch `bug-2-missing-sqlite3-bindings` then:

**Windows 10**

```
$ ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=win32 --target_arch=x64 --target=12.19.0
$ npm run electron:build:windows
```

**MacOS**

I first had to edit the `vue.config.js` with the following:

```
@@ -22,7 +22,7 @@ module.exports = {
         mac: {
           target: [
             {
-              target: "dmg",
+              target: "mas",
             },
           ],
         }

```
then ran
```
$ ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=darwin --target_arch=x64 --target=12.19.0
$ npm run electron:build:mac
```

**Comment by Alekxanderz** [comment]
We're glad we could help!

Thank you for bringing up the issue so we could give it a look, this should make the process for future releases a lot easier for us.

I'll be merging the changes into the main branch and closing the issue.
